### ISSUE TITLE
input camera information to render

### ISSUE THREAD

**Issue by jwzxgy2007** [jkulhanek/nerfbaselines#1]
This is a great job that has saved me a lot of time, thank you! Is it possible to support inputting a given camera parameter file for rendering, as sometimes it needs to be made into a video?

**Comment by jkulhanek** [comment]
Not yet, I will add support.

**Comment by jkulhanek** [comment]
But, by the way, in the meantime, you can easily load a trained checkpoint and use the unified python API to render anything.

**Comment by jkulhanek** [comment]
Hi, it is now implemented (in main) and will be included in the next release.
