### ISSUE TITLE
Nerfstudio configuration on Blender data

### ISSUE THREAD

**Issue by jb-ye** [jkulhanek/nerfbaselines#2]
I saw quite different results of nerfstudio on blender data as reported in https://jkulhanek.com/nerfbaselines/

```
ns-train nerfacto --data materials --pipeline.model.disable_scene_contraction=True --pipeline.model.use_appearance_embedding=False --pipeline.model.camera_optimizer.mode=off --output-dir train blender-data
```

I am getting 26.3 PSNR on material example rather than 17.595 as reported. 

I am checking the config here: https://github.com/jkulhanek/nerfbaselines/blob/main/nerfbaselines/methods/_impl/nerfstudio.py#L225

Where did you obtain the configuration setting for blender set?

**Comment by jkulhanek** [comment]
Hi, I took it from the siggraph paper branch in nerfstudio repo. I broke the nerfstudio after I upgraded the version to the newest one. Check the old result: https://github.com/jkulhanek/nerfbaselines/blob/1921e209da251e609ff4bf12e39f1a7ade245c16/results/nerfacto/blender/materials.json#L22

I will fix it, thanks for reporting!

**Comment by jkulhanek** [comment]
@jb-ye, actually, https://github.com/nerfstudio-project/nerfstudio/pull/2834 seems to be the culprit for Blender. When I disable it I get back to 25.6.

**Comment by jb-ye** [comment]
This is inconsistent with my finding: I am running with the three parameters using the latest nerfstudio (disable scene contraction, appearance embedding and camera opt) and get 26.3. This is with average initial density set to 0.01.

**Comment by jkulhanek** [comment]
So are you using the disparity sampler? https://github.com/nerfstudio-project/nerfstudio/blob/ffe3c31c13725684b90d3e84574244ed5b60f7e5/nerfstudio/model_components/ray_samplers.py#L225

**Comment by jb-ye** [comment]
Yes, I think so. Let me try uniform sampler of the proposal net as well.

**Comment by jkulhanek** [comment]
I ran it again with the same params, just adding the init_avg_density=0.01, and I got again psnr ~19 on the materials scene. It really makes a difference for me. I have no idea why it behaves differently for you. Can you please try adding all the other parameters to match my setup?

**Comment by jkulhanek** [comment]
I took the params from here: https://github.com/nerfstudio-project/nerfstudio/blob/ffe3c31c13725684b90d3e84574244ed5b60f7e5/nerfstudio/scripts/benchmarking/launch_train_blender.sh#L31 But it cannot be the same as in the paper as they are not disabling appearance embedddings

**Comment by jb-ye** [comment]
I can mimic the exact setup as yours and reproduced the same PSNR (17.85).

I think this command now make senses to me:
```
ns-train nerfacto --data materials \
--pipeline.model.near_plane 2 \
--pipeline.model.far_plane 6 \
--pipeline.model.proposal_initial_sampler uniform \
--pipeline.model.background_color white \
--pipeline.model.disable_scene_contraction=True \
--pipeline.model.use_appearance_embedding=False \
--pipeline.model.camera_optimizer.mode=off \
--pipeline.model.average_init_density 0.5 \
--output-dir train blender-data
```

where for a bounded scene, we probably should set average init density to a normal scale `(far_plane - near_plane) / 2`. I was able to get PSNR 26.27.

Another thing is I still think we should keep distortion loss rather than disabling it.

**Comment by jkulhanek** [comment]
I think this is resolved already.
