### ISSUE TITLE
Does Gaussian splatting support fisheye cameras?

### ISSUE THREAD

**Issue by m-mousatat** [jkulhanek/nerfbaselines#4]
Thank you very much for you collected training results, I am wondering that you mentioned here "https://jkulhanek.com/nerfbaselines/m-gaussian-splatting" that  Official Gaussian Splatting implementation extended to support distorted camera models. It is fast to train (1 hous) and render (200 FPS).

is that mean it started supporting fisheye camera? according to my knowledge it only supports pinhole.

do you have idea how to train 3GS on fisheye images?

**Comment by jkulhanek** [comment]
Hi, images are automatically undistorted before training and distorted after render.

**Comment by jkulhanek** [comment]
Fisheye models are supported, but I haven’t verified if the undistortion is 100% correct. In the new release I will be switching to opencv undistortion.

**Comment by Yochengliu** [comment]
> Fisheye models are supported, but I haven’t verified if the undistortion is 100% correct. In the new release I will be switching to opencv undistortion.

@jkulhanek   Hi, is opencv_undistortion implemented in the latest release?

**Comment by jkulhanek** [comment]
Hi, the undistortion is implemented for all camera models and the tests seem to be passing. But I will probably switch to an existing undistortion code (perhaps opencv) to avoid having to maintain the undistortion code myself. Have you had any issues with the current release?

**Comment by Yochengliu** [comment]
> the undistortion is implemented for all camera models and the tests seem to be passing.
@jkulhanek  Great! I want to know how "images are automatically undistorted before training and distorted after render". Does it mean that you don't modify the cuda code in "diff-gaussian-rasterization"? You just undistort fish-eye images before inputting them into the Gaussian splatting model, then distort GS-rendering images back to fish-eye images, so as to compute render loss for training. How about training and test results on some fish-eye datasets? Thanks.
