### ISSUE TITLE
Support for FULL_OPENCV

### ISSUE THREAD

**Issue by pgr-me** [jkulhanek/nerfbaselines#5]
Hello - I was wondering if / when you're planning on adding support for the FULL_OPENCV camera model. If there are no plans to do so in the near term, do you know how / whether I could convert FULL_OPENCV to vanilla OPENCV? Thanks!

**Comment by jkulhanek** [comment]
Hi, I don't understand the issue. FULL_OPENCV is fully supported in cameras.py. It is not supported by some methods, though. Which methods do you want to use?

**Comment by jkulhanek** [comment]
Also, for camera models which are not supported, there should be an automatic conversion to pinhole so full_opencv should also work for other methods. I haven't checked if this works with the latest code though...

**Comment by jkulhanek** [comment]
Closing as FULL_OPENCV is supported.
