### ISSUE TITLE
gsplat metrics

### ISSUE THREAD

**Issue by maturk** [jkulhanek/nerfbaselines#7]
Hey @jkulhanek, I am wondering if you are interested in adding the results of gsplat into your baseline comparisons as well? Currently, from my findings, some features in gsplat definitely beat the current metrics reported for gaussian-splatting (Inria based) and rival and possibly even beat the ZiP-NeRF metrics on some scenes.

Let me know... I could help out with this if you would be interested.

**Comment by jkulhanek** [comment]
Hi @maturk, Thanks! I will integrate it soon. It is very high on my priority list.

**Comment by jkulhanek** [comment]
Added in #15
